#!/bin/bash

#SBATCH --job-name=MGDA_UB_dynamic_stable
#SBATCH --mem=60G
#SBATCH -t 23:50:00
#SBATCH --gres=gpu:tesla_a100:1
#SBATCH --partition=tier1_gpu
#SBATCH --account=shinjini_kundu
##SBATCH --exclude=gpu01
#SBATCH --output=slurm-%A_haha.out
#SBATCH --error=slurm-%A_haha.err

module load cuda/12.9
module load cudnn/9.11.0.98-cuda12


. ~/miniconda3/bin/activate
conda activate pasta



python main.py




