#!/bin/bash

#SBATCH --job-name=brain_mask
#SBATCH --mem=5G
#SBATCH -t 23:50:00
#SBATCH --gres=gpu:1
#SBATCH --partition=tier1_gpu
#SBATCH --account=shinjini_kundu
#SBATCH --exclude=gpu02
#SBATCH --output=slurm-%A_haha.out
#SBATCH --error=slurm-%A_haha.err

module load cuda/11.3
module load cudnn/8.1.1

. ~/miniconda3/bin/activate
conda activate pasta



python fdg_tau_comparison.py




