#!/bin/bash
#SBATCH --job-name=gan_transform_infer
#SBATCH -N 1
#SBATCH --mem=32G
#SBATCH -t 08:00:00
#SBATCH --gres=gpu:tesla_a100:1
#SBATCH --partition=tier2_gpu
#SBATCH --account=shinjini_kundu
#SBATCH --exclude=gpu02,gpua405,gpu01
#SBATCH --output=slurm-%A_gan_transform_infer.out
#SBATCH --error=slurm-%A_gan_transform_infer.err

set -euo pipefail

module load cuda/12.2
module load cudnn/9.6.0.74-cuda12

. ~/miniconda3/bin/activate
conda activate pasta

export PYTHONUNBUFFERED=1
export ROOT_DIR="/scratch/l.peiwang/kari_flair_all"
export FOLD_INDEX=4

# Use the baseline model for the same fold you want to visualize.
export BASE_PRETRAIN_CKPT="/home/l.peiwang/MRI2PET/2025baseline_flair_fold5_os65/checkpoints/best_G.pth"
export OUT_TRANSFORM_DIR="/scratch/l.peiwang/gan_transform_infer/fold5_train"

mkdir -p "${OUT_TRANSFORM_DIR}"

python -u tools/infer_baseline_gan_transforms.py \
  --checkpoint "${BASE_PRETRAIN_CKPT}" \
  --out-dir "${OUT_TRANSFORM_DIR}"
